name: Run Daily Tasks
on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  daily_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Update Main leaderboards
        run: npm run main
        env:
          CLICKHOUSE_URL: ${{ secrets.CLICKHOUSE_URL }}
          CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}
          OVERALL: ${{ secrets.OVERALL }}
          SKILL: ${{ secrets.SKILL }}
          STYLE: ${{ secrets.STYLE }}
          FISHING: ${{ secrets.FISHING }}
          REPUTATION: ${{ secrets.REPUTATION }}
          BONUS: ${{ secrets.BONUS }}

      - name: Update Faction leaderboards
        run: npm run factions
        env:
          API_KEY: ${{ secrets.API_KEY }}
          FACTIONS: ${{ secrets.FACTIONS }}
          CLICKHOUSE_URL: ${{ secrets.CLICKHOUSE_URL }}
          CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}

      - name: Update Exchange Listings
        run: npm run exchange
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GAMES: ${{ secrets.GAMES }}
          CLICKHOUSE_URL: ${{ secrets.CLICKHOUSE_URL }}
          CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
